### ISSUE TITLE
测试阶段也需要输入阴影mask吗？

### ISSUE THREAD

**Issue by CanshangD** [xuyimin0926/SADC#1]
如果没有mask，只有测试原图，怎么测试呢？

**Comment by yuanyufang** [comment]
wawawa,i just look the paper,now look code,find,somebody also look,ye,find firend.

**Comment by lmbxmu** [comment]
> 如果没有mask，只有测试原图，怎么测试呢？

用一个mask detector得到mask

**Comment by cdzheng2g** [comment]
测试阶段的图片A、B、C这三类 都是必须要的嘛，我只有A、B怎么完成测试
