### ISSUE TITLE
关于阴影去除之后与原图unshadow部分的色差问题

### ISSUE THREAD

**Issue by LoveU3tHousand2** [xuyimin0926/SADC#2]
Hello, 你好，您的这个模型我训练了一晚上 现在来看 在ISTD的去阴影结果是不错的， 但是非阴影部分与原图会存在色差。
造成此原因可能是ISTD数据集本身ShadowImage和GT之间就存在色差， 也有可能就是并没有增加损失函数对unshadow部分的颜色进行约束； 
我这边将网络输出out = out *mask + img * (1 - mask) 作为输出和损失函数的输入，shadow与unshadow之间就可能会有色差、痕迹

想请教一下您是如何解决这个问题的？

**Comment by xuyimin0926** [comment]
您好，

我们是通过一个损失去减少两个区域之间的色差的。具体损失请参考我们文章的3.3部分。实验的结果可以再文章图5看出来，这个损失函数对边缘的色差有很大的修复效果。

非阴影区域和和原图的色差，我们现在已经可以达到SOTA的一个效果，如果进一步提升的话我们认为可以考虑将SADC模块和intra-loss应用到更强大的网络backbone上看看会不会有性能上的提升。

**Comment by LoveU3tHousand2** [comment]
谢谢您的回复，对我非常有帮助， 的确intra-loss对ghost边缘的去除是很有帮助的。
在这个去阴影效果的前提下， 我这边更关注的还是非阴影区域和原图的色差， 因为如果考虑到对大图的一个预测后拼接，不知道在保证效果的前提能不能就使用原图的unshadow部分。。。

**Comment by xuyimin0926** [comment]
如果shadow image的unshadow部分和原图（ground truth）基本无色差，可以直接用shadow image的无阴影区域作为最后输出的无阴影部分的。

**Comment by LoveU3tHousand2** [comment]
好的 谢谢～
